export const TASKS = {
  'Content Creation': {
    title: 'Content Creation',
    instructions: [
      'You have just been hired as a content creator for your company. Your job in this task will be to create social media captions by using the prompts below.  Please use the AI to help you do it.',
      'Please copy and paste the non-highlighted portion in the generate field and replace the highlighted portion with a scenario of your choosing (i.e. the examples).',
      'Write a 50 word tweet about <mark>a project</mark> (i.e. construction, graphic design, marketing).',
      'Write a funny and short instagram caption about <mark>a new initiative in your workplace</mark> (i.e. release of a paper, success of a product launch, creating a demo).',
      'Write a sarcastic and short instagram caption about <mark>a celebration</mark> (i.e. birthday, work anniversary, end of fiscal year).',
      'Write a facebook post to summarize <mark>the initiatives in your workplace</mark> (i.e. Mental health initiative, Volunteer initiative, Charity Drive, Strategic plan launch).',
      'Promote <mark>an object</mark> (i.e. furniture, electronics, appliances) so that someone will buy it on an online marketplace.',
      'Write a meaningful post about <mark>your workplace</mark>.',
      'If the AI tool is not generating a response, please refresh the page. The timer will begin again from the beginning.',
    ],
  },
  'Interview Questions': {
    title: 'Interview Questions',
    instructions: [
      'You have been asked to prepare some interview questions. Please use the AI to create questions for each scenario.',
      'Please copy and paste the non-highlighted portion in the generate field and replace the highlighted portion with a scenario of your choosing. The information in the brackets are suggestion for you to try.',
      'Create 10 questions for hiring a <mark>work position</mark> (i.e. car salesman, nurse, etc).',
      'Create 8 interview questions for a research study on a <mark>topic</mark> (customer satisfaction, patient experience, etc).',
      'Create 4 preliminary screening questions for hiring <mark>a position</mark>.',
      'If the AI tool is not generating a response, please refresh the page. The timer will begin again from the beginning.',
    ],
  },
  'Making Predictions': {
    title: 'Making Predictions',
    instructions: [
      'Give the AI the following prompts and judge the quality of its answers.',
      'Please copy and paste the prompts into the generate section within the AI tool.',
      'Will Twitter increase its users in 2023?',
      'What will be the exchange rate for euros and dollars in 2025?',
      'Will we see a growth in news items written by AI?',
      'Will we see a growth or decline in customers ordering food online?',
      'If the AI tool is not generating a response, please refresh the page. The timer will begin again from the beginning.',
    ],
  },
  'Fact Checking': {
    title: 'Fact Checking',
    instructions: [
      'Please use the following websites to find a headline and ask AI to fact check it.',
      'Q: Is Los Angeles the capital of California?',
      "Q: What is Cher's last name?",
      'Q: Who won the World cup in 2022?',
      'Q: Humans are classified as what species?',
      'Q: What continent is Italy located in?',
      'Q: How many moons does the Earth have?',
      'Q: Who is the founder of Apple?',
      'Q: What are the five major food groups?',
    ],
  },
  'Writing a Recommendation Letter': {
    title: 'Writing a Recommendation Letter',
    instructions: [
      'Please use the AI to write a recommendation letter based on the scenarios below:',
      'Please copy and paste the prompts into the generate section within the AI tool and replace the highlighted portion. You may use the prompts given in the brackets.',
      'Write a recommendation for a former colleague in your marketing company. The colleague did a relatively good job and was friendly with others.',
      'Write a recommendation for a current intern for a position in financial consulting company.',
      "Write a recommendation letter for <mark>a scholarship</mark> based on the scholarship's criteria (i.e. Rhodes Scholarship, McArthur Fellowship, Marshall scholarships).",
      '*Fill in the highlighted segments based on your personal experiences.',
      'If the AI tool is not generating a response, please refresh the page. The timer will begin again from the beginning.',
    ],
  },
};
